#spring:
#  datasource:
#    url: jdbc:h2:./devdb
#    username: sa
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        globally_quoted_identifiers: true
 
spring:
  datasource:
    generate-unique-name: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
      javax:
        persistence:
          validation:
            mode: none
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100        
  #jackson:
  #  mapper:
  #   DEFAULT_VIEW_INCLUSION: true #JSONView ile map edebilmesi için
      
server:
  port: '8090'
#logging:
#  level:
#    '[org.springframework]': DEBUG            
       
  
    
